### ISSUE TITLE
Stand Alone

### ISSUE THREAD

**Issue by DamieFC** [terrycojones/daudin#13]
Do you think there will ever be a stand alone version of this? Also, this is _**AWESOME**_.

**Comment by terrycojones** [comment]
Hey. Glad you like it :-)  What do you mean by a standalone version?  Thanks for the comment!

**Comment by DamieFC** [comment]
I mean if maybe if it will become it's own command line, maybe for unofficial purposes, for fun? 😃

**Comment by reckoner** [comment]
@DamieFc it sounds like you are asking for daudin to become its own shell, like bash?

**Comment by DamieFC** [comment]
Yes.

**Comment by reckoner** [comment]
You might want to check out xonsh. https://xon.sh/
