### ISSUE TITLE
History

### ISSUE THREAD

**Issue by john9631** [terrycojones/daudin#5]
Just started experimenting with daudin & I'm enjoying the shell, python mix.  This is really nice.

In the past I've also looked at pipeline oriented tools like pyp and piep.

The one thing that is immediately missing seems to be zsh's search through history.   Typing part of a command and then up arrow through the matches is a major part of my day.  Is this replicable?

**Comment by terrycojones** [comment]
Hi @john9631  I tried to reply a couple of days ago but somehow my reply got zapped. I'm glad you like daudin! I've not heard of pyp or piep, but will investigate.

The history search you describe seems to be like that of fish https://fishshell.com/  The "other" school of history search is the bash interactive search on control-r.  I don't know how it feels in zsh, but the way history search is implemented in fish is really painful for a long-time bash (and emacs) user. In fish you can type some text then move up/down in the history looking for that text but you can't then just keep typing more text to refine the search text. Maybe zsh is better like that. Anyway, daudin has the control-r history search that's provided by readline and present in bash and all other programs that use the readline library. Are you familiar with it?  There's a very long fish GitHub issue with many people requesting that fish use the bash approach.

BTW,  do you know https://github.com/junegunn/fzf ?  It's pretty good, but I haven't used it enough to really know it well.  Might be a solution.

Thanks again for commenting.

**Comment by john9631** [comment]
Thanks for the reply Terry.

I use fzf in vim & also at command line in zsh so I'll experiment within daudin.    I'm a CTA for MITx 6.00.1x and 6.00.2x and use ptpython and ptipython in terminal when responding to simple issues so I'm familiar with Ctrl R in that environment and will experiment with it now in daudin.

Take a look at ptpython some time. Its an enhanced python or ipython shell that's particularly good for vim users because you can switch to vim & back at a keystroke.

**Comment by john9631** [comment]
Yes.  Its good thanks.
