### ISSUE TITLE
How this compares to xonsh

### ISSUE THREAD

**Issue by jnoortheen** [terrycojones/daudin#6]
It is good to see someone trying to innovate in the space of develop tools. But duplicate efforts could be avoided. There is [xonsh](https://xon.sh/index.html) which is a superset of Python. It does define some extra constructs but very minimal. How does `daudin` compares to `xonsh`?

**Comment by terrycojones** [comment]
Hi @jnoortheen Someone else also pointed me to xonsh. I've not had a chance to look at it in any detail yet. But my first impression is that xonsh is quite a mature project. Daudin is something I wrote most of in one night. I can't really say what the differences are in any detail. xonsh seems to have a lot of "extra" functionality that must be provided by more careful parsing of the command line (e.g., a "normal" `cd` command), whereas daudin just splits on `|` that's not preceded by a backslash. Daudin allows anything to be in the pipeline (in the `_` variable). I have no idea what xonsh does, though I see it has pipelines.  That's all that comes to mind at the moment. Daudin was really me playing around to see what I could come up with. I wouldn't recommend it for serious use, at least not at this stage. xonsh looks very mature and is almost certainly much more robust, etc., and I assume has a decent community of people actually using it. I'm just playing around with ideas to see where they go and to have some fun.

**Comment by jnoortheen** [comment]
OK understood. I came here after reading about new shell in Python in PyCoders weekly newsletter and thought of letting you know about xonsh.

**Comment by terrycojones** [comment]
Ah, I didn't know it had been mentioned in PyCoders weekly newsletter (or even that that existed). That's interesting. Anyway, daudin is just a tiny, baby side-project at the moment. I'd be happy for people to contribute to it, of course, but don't have any ambitious plans for it myself at this point - I have too much other stuff to be doing.  But I think I'll start using it, just to see how it goes and probably will continue to make improvements.  Thanks!

**Comment by anki-code** [comment]
Hey @terrycojones! Your vision of pipelines and shortcuts around `_` look interesting. It will be cool if most of useful approaches not stay just a fun and sometime would be packed as a xontrib for xonsh. It has bigger community and your most greatest ideas would supported. Thanks!
