### ISSUE TITLE
Tab completion for Python modules as with IPython.

### ISSUE THREAD

**Issue by reckoner** [terrycojones/daudin#7]
Is this possible? I can't remember all the methods and attributes I need.

**Comment by terrycojones** [comment]
Yes, this is possible. I saw some code for it when I was reading about how to do filenames. I'll take a look...

**Comment by terrycojones** [comment]
OK, this looks very easy. I'll do it later today/tonight.

**Comment by reckoner** [comment]
great! I'll pull and test it as soon as you have it ready

**Comment by terrycojones** [comment]
OK, try `pip install -U daudin` and you should have it! Thanks for the suggestion :-)

**Comment by reckoner** [comment]
works like a dream!

**Comment by terrycojones** [comment]
OK, great. I'll close this.
